### ISSUE TITLE
Change rent button to Watch Now when canWatchNow is true

### ISSUE THREAD

**Issue by popand** [popand/webclient#16]
When a user is logged in and getting productDetails for a movie - if "canWatchNow":true display the button as "Watch Now" otherwise if "canWatchNow":false display the "Rent - $1.99"

![image](https://cloud.githubusercontent.com/assets/637144/11449107/11c97050-9538-11e5-9daf-ef5ee2ac42e0.png)

**Comment by meowcoder** [comment]
b425fe862a9ee8db0980d9babe553c89bf9caf25 should fix this.

Before: show "Watch Now" if `canWatchNow` is `true`, otherwise show "Rent".
After: show "Watch Now" if `canWatchNow` is `true` and user is logged in, otherwise show "Rent".

**Comment by popand** [comment]
Great for thinking to include if logged in to show the WatchNow button.
