### ISSUE TITLE
Braintree dropin ui intergrartion

### ISSUE THREAD

**Issue by popand** [popand/webclient#17]
The drop in ui should be used when an authenticated user selects the "Rent" or "Buy" button in product details.

![image](https://cloud.githubusercontent.com/assets/637144/11449664/0ec61f8e-954c-11e5-9d66-1dc1039b5acc.png)

https://developers.braintreepayments.com/guides/drop-in/javascript/v2

Please use the following api to acquire a token for the dropin ui:

```GET http://54.165.55.11:8765/purchaseservice/v1/purchase/client_token```

response:
```"eyJ2ZXJzaW9uIjoyLCJhdXRob3JpemF0aW9uRmluZ2VycHJpbnQiOiJjNTQwNWY5MjJkOGI3YWNmZDAyNDNmMjMwYWRmNjQwZjYyNTRjMDdmMThjYzg2MWQ4Mjk1YmU2YThiZTdiNjc2fGNyZWF0ZWRfYXQ9MjAxNS0xMS0yOFQwMToyNzoxNS4xNDQ3MjQzODQrMDAwMFx1MDAyNm1lcmNoYW50X2lkPWRkZDQ0Z3lucG16Y3c0NWZcdTAwMjZwdWJsaWNfa2V5PWI0dm45ODk4OWM3eHM3ZG4iLCJjb25maWdVcmwiOiJodHRwczovL2FwaS5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tOjQ0My9tZXJjaGFudHMvZGRkNDRneW5wbXpjdzQ1Zi9jbGllbnRfYXBpL3YxL2NvbmZpZ3VyYXRpb24iLCJjaGFsbGVuZ2VzIjpbXSwiZW52aXJvbm1lbnQiOiJzYW5kYm94IiwiY2xpZW50QXBpVXJsIjoiaHR0cHM6Ly9hcGkuc2FuZGJveC5icmFpbnRyZWVnYXRld2F5LmNvbTo0NDMvbWVyY2hhbnRzL2RkZDQ0Z3lucG16Y3c0NWYvY2xpZW50X2FwaSIsImFzc2V0c1VybCI6Imh0dHBzOi8vYXNzZXRzLmJyYWludHJlZWdhdGV3YXkuY29tIiwiYXV0aFVybCI6Imh0dHBzOi8vYXV0aC52ZW5tby5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tIiwiYW5hbHl0aWNzIjp7InVybCI6Imh0dHBzOi8vY2xpZW50LWFuYWx5dGljcy5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tIn0sInRocmVlRFNlY3VyZUVuYWJsZWQiOnRydWUsInRocmVlRFNlY3VyZSI6eyJsb29rdXBVcmwiOiJodHRwczovL2FwaS5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tOjQ0My9tZXJjaGFudHMvZGRkNDRneW5wbXpjdzQ1Zi90aHJlZV9kX3NlY3VyZS9sb29rdXAifSwicGF5cGFsRW5hYmxlZCI6dHJ1ZSwicGF5cGFsIjp7ImRpc3BsYXlOYW1lIjoiUHJpdmF0ZSIsImNsaWVudElkIjpudWxsLCJwcml2YWN5VXJsIjoiaHR0cDovL2V4YW1wbGUuY29tL3BwIiwidXNlckFncmVlbWVudFVybCI6Imh0dHA6Ly9leGFtcGxlLmNvbS90b3MiLCJiYXNlVXJsIjoiaHR0cHM6Ly9hc3NldHMuYnJhaW50cmVlZ2F0ZXdheS5jb20iLCJhc3NldHNVcmwiOiJodHRwczovL2NoZWNrb3V0LnBheXBhbC5jb20iLCJkaXJlY3RCYXNlVXJsIjpudWxsLCJhbGxvd0h0dHAiOnRydWUsImVudmlyb25tZW50Tm9OZXR3b3JrIjp0cnVlLCJlbnZpcm9ubWVudCI6Im9mZmxpbmUiLCJ1bnZldHRlZE1lcmNoYW50IjpmYWxzZSwiYnJhaW50cmVlQ2xpZW50SWQiOiJtYXN0ZXJjbGllbnQzIiwiYmlsbGluZ0FncmVlbWVudHNFbmFibGVkIjpmYWxzZSwibWVyY2hhbnRBY2NvdW50SWQiOiJmeGh5enc1cTVwNGQ0YzNqIiwiY3VycmVuY3lJc29Db2RlIjoiVVNEIn0sImNvaW5iYXNlRW5hYmxlZCI6ZmFsc2UsIm1lcmNoYW50SWQiOiJkZGQ0NGd5bnBtemN3NDVmIiwidmVubW8iOiJvZmYifQ==" ```

When Completing the checkout the dropin ui will provide the ability to call the following api to complete the checkout:

http://54.165.55.11:8765/purchaseservice/swagger#!/purchase-controller/checkout_post_0

POST http://54.165.55.11:8765/purchaseservice/v1/purchase/checkout

{
  "paymentNonce": "string",
  "offer": "Offer",
  "productId": "string"
}

paymentNounce: is provided by the dropin ui based on payment selected
offer:  can get from the following api - http://54.165.55.11:8765/offerservice/v1/offer/{offerId}
productId: from productDetails of the selected product

**Comment by meowcoder** [comment]
I get the following error on checkout:

```json
{
    "timestamp": 1448700108112,
    "status": 500,
    "error": "Internal Server Error",
    "exception": "java.lang.NullPointerException",
    "message": "org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException",
    "path": "/purchaseservice/v1/purchase/checkout"
}
```

I pushed the changes, so you can debug it.

**Comment by popand** [comment]
I will look into it.  Can you please share the request?

**Comment by popand** [comment]
I've updated the checkout api to now accept offerId and price as supposed to having to provide a full offer.

i.e. 
POST http://54.165.55.11:8765/purchaseservice/v1/purchase/checkout
{
  "paymentNonce": "string",
  "price": "string",
  "offerId": "string",
  "productId": "string"
}

Can you please give this one a try and if you encounter an exception again, please send me the request.

Thanks
